Explain why piracy sites can't be included
yt-dlp/yt-dlp-wiki pull request #41
Opened 2024-08-23 23:34 UTC by seproDev

2024-08-24 06:16 UTC, pzhlkj6612 requested changes

2024-08-24 06:16 UTC, pzhlkj6612 commented on FAQ.md
> +- It is difficult to find a single non pirated video
```suggestion
- It is difficult to find a single non-pirated video
```

2024-09-12 20:57 UTC, bashonly requested changes

2024-09-12 20:57 UTC, bashonly commented on FAQ.md
> +The short answer is that supporting piracy sites could both get the project shut down and the maintainers into legal trouble.
keep it simple IMO
```suggestion
The short answer is that supporting piracy sites would in all likelihood result in the project being shut down.
```

2024-09-12 20:57 UTC, bashonly commented on FAQ.md
> +- It is difficult to find a single non pirated video
```suggestion
- It is difficult to find a single non-pirated video on the site
```

2024-09-12 20:57 UTC, bashonly commented on FAQ.md
> +This list is not exhaustive. It is up to the discretion of the maintainers if a site will be included in yt-dlp or not.
```suggestion
This list is not exhaustive. It is up to the discretion of the maintainers as to whether or not a site will be included in yt-dlp.
```

2024-09-12 20:57 UTC, bashonly commented on FAQ.md
> +The current maintainers of yt-dlp have decided that they are not willing to take that risk.
I would consolidate these two lines and maybe omit the bit about forking
```suggestion
The yt-dlp maintainers are of the position that supporting these sites would be of no benefit to the project, but rather that doing so would only put the project's continued existence at risk.
```

2024-10-22 20:51 UTC, bashonly approved these changes

2024-10-22 20:51 UTC, bashonly commented on FAQ.md
> +The yt-dlp maintainers are of the position that supporting these sites would be of no benefit to the project, but rather that doing so would only put the project's continued existence at risk.
```suggestion
The yt-dlp maintainers are of the position that supporting such sites is not worth the risk.
```

2024-10-23 03:01 UTC, pzhlkj6612 reviewed
Looks OK!

2024-10-23 20:36 UTC, merged